server:
  port: 9082
  servlet:
    context-path: /restService

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    serialization:
      write-dates-as-timestamps: true
      write-enums-using-index: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb2
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: update


